package com.nomes72.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — based on #147A8C (teal/petrol blue)
val PrimaryLight = Color(0xFF147A8C)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFE0F4F7)
val OnPrimaryContainerLight = Color(0xFF0D4F5A)
val SecondaryLight = Color(0xFF4A6267)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFEDF5F7)
val OnSecondaryContainerLight = Color(0xFF2A4448)
val BackgroundLight = Color(0xFFFAFDFD)
val OnBackgroundLight = Color(0xFF1A2C2F)
val SurfaceLight = Color(0xFFFAFDFD)
val OnSurfaceLight = Color(0xFF1A2C2F)
val SurfaceVariantLight = Color(0xFFF0F5F6)
val OnSurfaceVariantLight = Color(0xFF3D5256)
val OutlineLight = Color(0xFFD0DBDD)

// Dark theme
val PrimaryDark = Color(0xFF7DD4E4)
val OnPrimaryDark = Color(0xFF003740)
val PrimaryContainerDark = Color(0xFF0F5D6A)
val OnPrimaryContainerDark = Color(0xFFD0EFF5)
val SecondaryDark = Color(0xFFB0CDD2)
val OnSecondaryDark = Color(0xFF1A3438)
val SecondaryContainerDark = Color(0xFF2A4448)
val OnSecondaryContainerDark = Color(0xFFD0E8EC)
val BackgroundDark = Color(0xFF0F1A1C)
val OnBackgroundDark = Color(0xFFDDE4E5)
val SurfaceDark = Color(0xFF0F1A1C)
val OnSurfaceDark = Color(0xFFDDE4E5)
val SurfaceVariantDark = Color(0xFF1A2C2F)
val OnSurfaceVariantDark = Color(0xFFB8C8CB)
val OutlineDark = Color(0xFF2D4245)